import './globals.css'
import { Inter } from 'next/font/google'
import { FlagshipProvider } from '@flagship.io/react-sdk'
import React, { JSX } from 'react'
import { ENV_ID, API_KEY } from '../config.js'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

// export const revalidate = 0

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
      <FlagshipProvider
      // decisionMode={ DecisionMode.BUCKETING }
      visitorData={{}}
      // initialFlagsData={initialFlagsData}
      // fetchNow={false}
      envId={ENV_ID}
      apiKey={API_KEY}
      nextFetchConfig={{ revalidate: 0 }}
    >
        {children}
        </FlagshipProvider>
        </body>
    </html>
  )
}
