name: Test & Code coverage
on:
    push:
        branches: [master]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Install modules
              run: yarn install
            - name: Run tests
              run: yarn run test
            - name: Upload codecov report
              uses: codecov/codecov-action@v4
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  file: ./coverage/clover.xml
                  flags: unittests
                  name: codecov-flagship-react-coverage
                  fail_ci_if_error: true
