name: Test
on:
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Enable Corepack
              run: corepack enable
            - name: Set Yarn Version
              run: corepack prepare yarn@4.7.0 --activate
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
                cache: "yarn"
                cache-dependency-path: yarn.lock
            - name: Install modules
              run: yarn install
            - name: Run tests
              run: yarn run test
