name: Test
on:
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Install modules
              run: yarn install
            - name: Run tests
              run: yarn run test
