name: NPM CD
on:
  push:
    tags: 
      - "[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Set Yarn Version
        run: corepack prepare yarn@4.7.0 --activate
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: yarn.lock
      - name: Install modules
        run: yarn install
      - run: yarn build
      - run: npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
