name: NPM CD
on:
  push:
    tags: 
      - "2.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install
      - run: yarn test --coverage
      - uses: codecov/codecov-action@v2
      - run: yarn build
      - run: npm publish --tag version.2
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}